source "https://rubygems.org"

gem "fastlane",           "~> 2.220"
gem "cocoapods",          "~> 1.15"
gem "xcodeproj",          "~> 1.24"

# Plugins
gem "fastlane-plugin-android_set_version_name"
gem "fastlane-plugin-increment_build_number"
